# Rotate per-channel logs
channels/*/output/ffmpeg.log {
    size 1000k
    rotate 2
    copytruncate
    missingok
    notifempty
    nocompress
}

channels/*/output/cleanup.log {
    size 1000k
    rotate 2
    copytruncate
    missingok
    notifempty
    nocompress
}

# Rotate main server log
output/server.log {
    size 1000k
    rotate 2
    copytruncate
    missingok
    notifempty
    nocompress
}

# Rotate on demand log
output/ffmpeg.log {
    size 1000k
    rotate 2
    copytruncate
    missingok
    notifempty
    nocompress
}
